- name: Disable iptables
  service: name=iptables state=stopped enabled=no
  when:
    - iptables_disable_iptables
    - ansible_distribution == "CentOS"

- name: Enable iptables
  service: name=iptables state=started enabled=yes
  when:
    - iptables_enable_iptables
    - ansible_distribution == "CentOS"

- name: Modify iptables
  template: src=iptables_rules.j2 dest="/etc/sysconfig/iptables" mode=0600
  when: 
    - iptables_modify_iptables
    - item.host == ansible_host
  with_items: "{{ iptables_role_sites }}"
 
  notify: restart iptables
