- name: Install base packages
  yum: name={{ item }} state=latest
  with_items:
    - gcc 
    - automake
    - autoconf
    - libtool
    - make 
    - gcc-c++ 
    - pcre-devel
    - zlib-devel
    - openssl-devel
    - wget 
    - lrzsz
 
- name: create nginx user
  user: name={{ nginx_user }} shell=/user/bin/false
  
- name: download nginx
  get_url:
    url: "{{ download_url }}/nginx-{{nginx_version}}.tar.gz"
    dest: "{{ download_dir }}"

- name: Unarchive nginx
  unarchive: 
    src: "{{ download_dir }}/nginx-{{ nginx_version }}.tar.gz"
    dest: "{{ download_dir }}"
    copy: no 

- name: Copy nginx install script
  template: src=nginx_install.j2 dest=/tmp/nginx_install.sh mode=0744

- name: Install nginx
  shell: "/bin/bash /tmp/nginx_install.sh"
  register: nginx_install_result

- name: Nginx revproxy setting
  template: src=nginx_config_file.j2 dest="{{ install_dir }}/conf/nginx.conf"
  when:
    - nginx_install_result is success
    - nginx_revproxy_config

- name: Copy nginx start scripts
  copy: src=nginx_start_scripts dest=/etc/init.d/nginx mode=0755
  when: 
    - nginx_install_result is success
    - nginx_start_scripts

- name: Start nginx service
  shell: /etc/init.d/nginx start
  when:
    - nginx_start_scripts
    - nginx_start_service

- name: Start nginx service on boot
  lineinfile: 
    path: /etc/rc.d/rc.local
    line: "/etc/init.d/nginx start >/dev/null 2>&1"
    mode: 0755
  when: 
    - nginx_start_scripts
    - nginx_start_on_boot 

- name: Add iptables
  shell: iptables -I INPUT -p tcp -m tcp --dport "{{ item }}" -j ACCEPT; service iptables save
  with_items:
    - "{{ item.value.listen_port | default:80 }}"
    - "{{ item.value.listen_port | default:443 }}"
  when:
    - add_iptables_for_nginx
    - item.key == ansible_host




