---
- hosts: proxy_server
  remote_user: root
  vars:
    nginx_revproxy_sites:                                     
      10.0.1.221:
        desc: t_server
        domains:
          - example.com
          - www.example.com
        upstreams:
          - { address: 192.168.10.1, port: 80}
          - { address: 192.168.10.12, port: 8080}
        listen_port: 9000
        listen_ssl_port: 9001
        ssl_status: true
        ssl_crt: /etc/ssl/test.com.crt;
        ssl_key:  /etc/ssl/test.com.key;
